name: CI/CD Pipeline

on: 
  push:
    branches: ["main", "feature*"]
    tags: ['v*']
  pull_request:
    branches: ["main", "feature*"]
    
jobs:
  ci:
    uses: Mark-Grigorev/central-ci-cd/.github/workflows/go-ci-complete.yml@main
    with:
      go-version: ${{ vars.GO_VERS }}
      linter-version: ${{ vars.LINTER_VERS }}
      ubuntu-version: ${{ vars.UBUNTU_VERS }}
